### ISSUE TITLE
New file name for csd creates double when rotated

### ISSUE THREAD

**Issue by kr-nahid** [gogins/csound-extended#34] opened 2018-05-22 16:38 UTC
#### Expected behavior
it shouldn't expected that file name creates double for screen rotated

#### Actual behavior
when i try to create a **New CSD** and put a file name , this file name creates twice name when screen rotated from portrait to landscape mode.

#### How to reproduce
* download the app
* open it and click on New
* then put a file name
* and now rotated device from portrait to landscape
* then see name creates twice 

> Browser : Csound for Android 6.11.1
 Operating system: android 5.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=U0knsr4yUQc

**Comment by gogins** [comment] 2018-05-22 19:05
Thank you for this bug report. I watched your video, and I saw the problem. Unfortunately, I cannot reproduce the problem myself. I tried several times.  I am on a Samsung Note 8, Android version 8.0.0. Therefore, I think this is an Android problem, and I am closing the issue. If you can reproduce the problem on more recent versions of Android, please re-open the issue.

**Closed by gogins** 2018-05-22 19:05 UTC
Labels: Android
