### ISSUE TITLE
Csound for Android app fractional instruments

### ISSUE THREAD

**Issue by ErrorThink** [gogins/csound-extended#98] opened 2019-07-19 11:51 UTC
Latest Android app in the store (labelled 6.12.0). 
When calling an instrument with a fractional instrument number using the event , event_i or schedule opcodes, the fractional part is ignored. Score lines (and the scoreline opcode) work fine. 
Example attached (remove .txt suffix).
[fracbug.csd.txt](https://github.com/gogins/csound-extended/files/3410947/fracbug.csd.txt)

**Comment by gogins** [comment] 2019-07-19 13:06
I have reproduced this bug. Both of the chords play properly, but, indeed, the Csound for Android app omits the fractional instrument number for the `event_i` opcode.

I have attached a more readable version of the example .csd that reproduces the bug.
[fracbug.csd.txt](https://github.com/gogins/csound-extended/files/3411175/fracbug.csd.txt)

**Comment by gogins** [comment] 2019-07-19 13:15
The Csound code appears to be in `eventOpcodeI_` at `linevent.c:516`. In all paths this function appears to call `strarg2insno`.

**Comment by gogins** [comment] 2019-07-19 13:38
I am closing this issue as not being a bug. The use case for the Csound for Android app involves Csound being run by the Google Oboe audio driver. This in turn means that when performing this test .csd, `eventOpcodeI_` is called by desktop Csound, and `eventOpcode_` is called by the Csound for Android app.

If you feel that this is still a bug, please re-open this issue in the Csound issue tracker and refer there to this issue, and request that the Csound code be changed, if possible, so that `eventOpcode_` and `eventOpcodeI` both do not cast the insno to an integer.

**Closed** 2019-07-19 13:43 UTC

**Comment by ErrorThink** [comment] 2019-07-19 14:05
I'm not sure I understand.This bug was found under with use case you describe: Using the Csound for Android app, with the oboe audio driver, on an Android tablet running Android 7.1.1. No dssktop version involved.

**Comment by gogins** [comment] 2019-07-19 15:57
To be clear, I am saying that this issue is not a bug FOR THE CSOUND FOR ANDROID APP because it cannot be fixed in the Csound for Android app source code. It can only be fixed in the Csound source code, hence since you have opened an issue in Csound, that was the right thing to do.
